[package]
name = "nordigen"
description = "Abstract Nordigen Open Banking API"
authors = ["Joao Eduardo Luis <joao@abysmo.io>"]
version = "0.1.0"
license = "Apache-2.0"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/jecluis/ob-nordigen-rs/"
keywords = ["open-banking", "nordigen"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.0.32", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.152", features = ["derive", "serde_derive"] }
serde_json = "1.0.91"
